### ISSUE TITLE
pngPath is not defined

### ISSUE THREAD

**Issue by slavikator** [BB-fat/electron-icns-ex#1]
Could you help me to figure out what am I missing? 

```
    const icns = require('electron-icns-ex');
    parseIcnsToPNG(localIconPath, pngPath);                         // localIconPath defined erlier in the code
    const img = document.querySelector("#localIcon");
    img.src = pngPath;
```
error:
`pngPath is not defined`

**Comment by BB-fat** [comment]
`pngPath` is the destination path where the converted icns file is stored, which is defined by you.

**Comment by slavikator** [comment]
That's what I understood. So, it seems nothing wrong with the code and still, I get an error.

**Comment by BB-fat** [comment]
try replace `parseIcnsToPNG(localIconPath, pngPath); ` to `icns.parseIcnsToPNG(localIconPath, pngPath); `

**Comment by slavikator** [comment]
Yes, I have done this before - the same error.

**Comment by BB-fat** [comment]
Can you show me more complete code and error? And did you try `icns.parseIcnsToBase64`?

**Comment by slavikator** [comment]
This is basically what is related to showing the image. 

rendere.js
```
    const localIconPath = ddPath + "/Contents/Resources/" + CFBundleName + ".icns";
    const icns = require('electron-icns-ex');
    icns.parseIcnsToPNG(localIconPath, pngPath);
    const img = document.querySelector("#localIcon");
    img.src = pngPath;
```

index.html
```
          <div>
            <img id="localIcon" src="">
          </div>
```

P.S.
The image displays if I replace the `img.src = pngPath` to `img.src = "pathtoimage.png"`, where pathtoimage.png is a test image saved locally.

**Comment by slavikator** [comment]
Didn't figure out how to use the `icns.parseIcnsToBase64`

**Comment by BB-fat** [comment]
There are two problems here.

1. This module is a native module, and **you can not use native module in the renderer process**. You should write these code in main process and pass the result to renderer process via IPC channel.
2. There is something wrong with your understanding here, maybe it's because my README is relatively simple and doesn't make it clear. The corrected code is as follows.
```javascript
// in main process
const localIconPath = ddPath + "/Contents/Resources/" + CFBundleName + ".icns";
const icns = require('electron-icns-ex');
const pngPath = '/tmp/test.png'; // To save the png file, you need to specify the path manually.
icns.parseIcnsToPNG(localIconPath, pngPath);

// in renderer process
const img = document.querySelector("#localIcon");
img.src = pngPath;
```

**Comment by slavikator** [comment]
Thanks for the explanation. This is my first Electron project,  definitely something wrong with my understanding here. ))

**Comment by BB-fat** [comment]
I'll close this issue, if there is still a problem you can reopen it.

**Comment by slavikator** [comment]
`const pngPath = '/tmp/test.png'; // To save the png file, you need to specify the path manually.`
I need to avoid saving the file. It seems the `icns.parseIcnsToBase64` must be used instead. 

Will this be correct then?

 // in main process
```
const localIconPath = ddPath + "/Contents/Resources/" + CFBundleName + ".icns";
const icns = require('electron-icns-ex');
const base64 = icns.parseIcnsToBase64(localIconPath);
```

// in renderer process
```
const img = document.querySelector("#localIcon");
img.src = base64;
```

**Comment by BB-fat** [comment]
That's right.
